defaults: &defaults
  app: &app
    title: Browet

development:
  <<: *defaults
  app:
    <<: *app
    host: browet.local:4200


test:
  <<: *defaults


production:
  <<: *defaults
  app:
    <<: *app
    host: browet.ru


staging:
  <<: *defaults
  app:
    <<: *app
    host: browet.ru